//CRIE UM PROJETO DE LISTA DE TAREFAS, ONDE UM USUÁRIO DEVE:
//CRIAR NOVAS TAREFAS EXCLUIR TAREFAS ATUALIZAR OS ESTADOS DAS TAREFAS
//VER TODAS AS TAREFAS QUE ELE POSSUI,
//CADA TAREFA PODE TER DIFERENTES FORMAS E DIFERENTES VALORES, PODENDO SER
//TRABALHO LAZER ESTUDOS ETC...
//FIQUE A VONTADE PARA IMPLEMENTAR OUTRAS FUNCIONALIDADES: AUTENTICAÇÃO,
//TELAS, ETC...
//PORÉM, O MAIS IMPORTANTE DO DESAFIO É APLICAR TODOS OS CONHECIMENTOS DE POO
//DE CLASSES E OBJETOS Á POLIMORFISMO.
//ESTE É UM DESAFIO PARA LHE TESTAR SE REALMENTE ESTÁ APTO PARA INGRESSAR
//NO MUNDO DO FLUTTER.
//EAI, POSSO CONTAR COM VOCÊ?

import 'package:final_challenge/interface/home_page_interface.dart';

import 'features/home.dart';

void main() {
  Navigator.init(Home());
}
